services:
  - type: web
    name: flask-agriculture-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: THINGSPEAK_API_KEY
        fromDashboard: true
      - key: THINGSPEAK_READ_KEY
        fromDashboard: true
      - key: THINGSPEAK_WRITE_KEY
        fromDashboard: true
      - key: THINGSPEAK_CHANNEL_ID
        fromDashboard: true
